l0o0/translators_CN

translators/PatentStar.js
1、修复已授权专利直接下载专利说明书而不下载专利申请书
2、修复http网址无法正常获取信息的错误
=> 修复专利之星PatentStar

translators/dpaper.js
感谢您们的贡献.
加入了中科院文献情报学位论文的支持,连接所内网络的时候可以获取学位论文的条目
刚开始学javascript,写的有点暴力.
=> feat: 支持中国科学院文献情报中心的学位论文

translators/Douban.js
=> fix: 豆瓣出版社抓取问题

translators/xiaoyuzhoufm.js
=> feat: 增加「小宇宙」播客抓取

translators/Wanfang Data.js
=> Fix Wanfang PDF download

translators/Spc.org.cn.js
1. 中国标准在线服务网的 html 有所调整，这里修复了 css selector。
2. 国标中“标准”的文献类型标识是“S”，与“法律”的“A”最好区分开。所以改为使用 report 文献类型，并且在 extra 中添加“Type: standard”（参考 <https://forums.zotero.org/discussion/comment/409058#Comment_409058>），这样可以在 CSL 中被正确识别为 standard 类型。
=> Fix: 更新中国标准在线服务网

translators/Wanfang Data.js
```
+ feat: standard in Wanfang Data as statute type
* use addExtra function for unified format
* do not split creator name if is labeled as a company
```
=> Feat: standard in Wanfang Data as statute type

translators/Wanfang Data.js
eg. https://d.wanfangdata.com.cn/periodical/ysxb98202209004
Before:
```json
"creators": [
{
"firstName": "计国"
"lastName": "刘"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "1"
"creatorType": "author"
}
{
"firstName": "凤云"
"lastName": "郑"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "1"
"creatorType": "author"
}
{
"firstName": "凤军"
"lastName": "毛"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "1"
"creatorType": "author"
}
{
"firstName": "虹"
"lastName": "姜"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "1"
"creatorType": "author"
}
{
"firstName": "早红"
"lastName": "李"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "1"
"creatorType": "author"
}
{
"firstName": "明胜"
"lastName": "吕"
"creatorType": "author"
}
{
"firstName": ""
"lastName": "2" …
```
=> Fix: affiliation numbers in author list when have multiple affiliations

translators/Duxiu.js
=> 读秀bug修正 & 读秀内期刊阅读的初步支持

translators/CNKI.js
=> fix: select PDF in deep child

translators/PKULaw.js
目前尚未实现的功能：
1. 从搜索结果批量抓取；
2. 期刊文章的 PDF 附件。
需要请教 @l0o0 。
=> 新增北大法宝转换器（#129）

translators/National Public Service Platform for Standards Information - China.js, translators/National Standards Open System - China.js, translators/Wanfang Data.js
`Wanfang Data.js` updated.
Solve #185
=> feat(standard item type support)

Wanfang Data.js
修复万方部分文章没有卷信息时导致翻译器失效
fix #207
=> fix(Wanfang Data.js): 修复万方部分文章没有卷信息时导致翻译器失效

WeiPu.js
涉及 #70、#90、#173，超时需要刷新网页（详见 https://github.com/l0o0/translators_CN/issues/70#issuecomment-1772671920 ）。
=> fix (WeiPu.js): 修复条目抓取失败；修缺ISSN字段

ChinaXiv.js
感谢 @yfdyh000 指路（[comment](https://github.com/l0o0/translators_CN/pull/224#issuecomment-1802474212)）。
=> fix (ChinaXiv.js) 修复extra乱码；增加备用抓取方案；优化姓名清洗算法；更新测试案例

Pishu Data.js
=> fix (Pishu Data.js) 适配vpn用户

data/data.json, data/translators.json
=> fix: data.json中label不对应

SuperLib.js
- 优化多条目selector
- 修复缺刊名
- 修复creators键未定义
- 更新测试案例
- 区分图书出版地和出版社名称
- 修复图书日期格式
- 移除过时的`processDocument()`函数
- 通过ESLint
=> fix (SuperLib.js) 修复作者名称未正常分割 (#241)

National Public Service Platform for Standards Information - China.js, National Standards Open System - China.js
另外我在 scaffold 保存的时候，`detectedItemType` 都删掉了，这是预期的行为吗？
=> 更新“全国标准信息公共服务平台”测试用例（#250）

Baidu Scholar.js
https://xueshu.baidu.com/usercenter/paper/show?paperid=59a44b761c61d8a9033990e15aa8eca6
=> fix(Baidu Scholar.js): book's ISBN

README.md, translators/Douban.js
支持识别豆瓣阅读的[出版图书](https://read.douban.com/ebooks/)（因为不像豆瓣读书那么规则，部分字段可能需要手动修改）
测试书籍：
https://read.douban.com/ebook/399488285/
https://read.douban.com/ebook/423420664/
=> feat(Douban.js):支持识别豆瓣阅读的出版图书

BiliBili.js
百度下来就是BiliBili了，正在逐步把LintIt更新过的翻译器迁移到主线。
=> fix (BiliBili.js) 通过ESLint；简化代码；更新测试用例

National Public Service Platform for Standards Information - China.js
=> feat (National Public Service Platform for Standards Information - China.js)支持多条目；支持行业和地方平台；更新测试用例

Ncpssd.js
解决了过去字段混用的问题，比如ISSN放到索书号之类。
似乎解决了#176 提到的PDF下载问题。
=> fix (Ncpssd.js) 修复字段占用；支持首页多条目下载；更新测试案例

Wanfang Data.js
Fix detection of standard type
Use 归口单位 as creators as instructed in GB/T 7714-2015 Appendix A.6
BREAKING CHANGE: 
1. Require minimum Zotero version 6.0.24. 
2. Standard full text PDF download now need to be done manually in browser after complete a purchase order.
=> fix(Wanfang Data.js): update scraper for standard type

SKCTK.js, data/data.json
=> add (SKCTK.js) 新增中国社会科学词条库

National Public Service Platform for Standards Information - China.js
=> Update National Public Service Platform for Standards Information - China.js

CNKI.js, E-Tiller.js
见 <https://github.com/l0o0/translators_CN/issues/257#issuecomment-1929406785>。
=> 修复网络首发日期：不再使用 available-date

Modern History.js, data/data.json
网址： <https://www.modernhistory.org.cn/#/>
期刊文章在Scaffold里面GET不到result，非常奇怪。
不知用`document`记录的“档案”条目是否合适。 @zepinglee
=> add (Modern History.js) 新增抗日战争与近代中日关系文献数据平台

Science Reading.js, data/data.json
=> add  (Science Reading.js) 新增科学文库 #138

NTU Digital Library of Buddhist Studies.js, data/data.json
resolve #174
@CallMeNP
@tzuifurther
=> add (NTU Digital Library of Buddhist Studies.js) 新增臺大佛學數位圖書館 #174

NDLTD.js, data/data.json
=> add (NDLTD.js) 新增臺灣博預士論文知識加值系統

Founder.js, data/data.json
多条目暂不打算支持，因为有一种类型（标题在 em 元素中）无法获得请求参数，而且我没有办法推断何时使用 `/thesisDetail`、何时使用 `/article/` 子路径。
@doubanchan close #366
=> add Founder

Zhihu.js
新增知乎网页爬取功能:
- 匹配收藏（collection），专栏（ column）页面字段
- 匹配每一个用户下的文章（posts）和回答（answers）字段
- 新增爬取文章（posts）功能
- 对公式进行转换
- 小卡片链接转换
- 去掉知乎直达链接
- 去掉知乎跳转
=> zhihu update
